import express from 'express'
import type { Request, Response, NextFunction } from 'express'
import cookieParser from 'cookie-parser'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { fileURLToPath } from 'node:url'
import db from './db.js'

const PORT = Number(process.env.PORT ?? 3001)
const JWT_SECRET = process.env.JWT_SECRET ?? 'dev-secret-change-in-production'
const COOKIE = 'token'

const app = express()
app.use(express.json())
app.use(cookieParser())

// Star/constellation datasets generated by scripts/build-data.mjs
const dataDir = fileURLToPath(new URL('../../data', import.meta.url))
app.use('/api/data', express.static(dataDir, { maxAge: '1h' }))

interface AuthedRequest extends Request {
  userId?: number
}

function getUserId(req: Request): number | null {
  const token = req.cookies?.[COOKIE]
  if (!token) return null
  try {
    const payload = jwt.verify(token, JWT_SECRET) as { uid: number }
    return payload.uid
  } catch {
    return null
  }
}

function requireAuth(req: AuthedRequest, res: Response, next: NextFunction) {
  const uid = getUserId(req)
  if (uid === null) {
    res.status(401).json({ error: 'Not logged in' })
    return
  }
  req.userId = uid
  next()
}

function setSession(res: Response, uid: number) {
  const token = jwt.sign({ uid }, JWT_SECRET, { expiresIn: '30d' })
  res.cookie(COOKIE, token, {
    httpOnly: true,
    sameSite: 'lax',
    maxAge: 30 * 24 * 60 * 60 * 1000,
  })
}

// --- Auth ----------------------------------------------------------------

app.post('/api/auth/register', (req, res) => {
  const { email, password } = req.body ?? {}
  if (typeof email !== 'string' || !/^\S+@\S+\.\S+$/.test(email)) {
    res.status(400).json({ error: 'Valid email required' })
    return
  }
  if (typeof password !== 'string' || password.length < 6) {
    res.status(400).json({ error: 'Password must be at least 6 characters' })
    return
  }
  const existing = db.prepare('SELECT id FROM users WHERE email = ?').get(email)
  if (existing) {
    res.status(409).json({ error: 'An account with that email already exists' })
    return
  }
  const hash = bcrypt.hashSync(password, 10)
  const info = db
    .prepare('INSERT INTO users (email, password_hash) VALUES (?, ?)')
    .run(email.toLowerCase(), hash)
  const uid = Number(info.lastInsertRowid)
  setSession(res, uid)
  res.status(201).json({ id: uid, email: email.toLowerCase() })
})

app.post('/api/auth/login', (req, res) => {
  const { email, password } = req.body ?? {}
  const user = db
    .prepare('SELECT id, email, password_hash FROM users WHERE email = ?')
    .get(String(email ?? '').toLowerCase()) as
    | { id: number; email: string; password_hash: string }
    | undefined
  if (!user || !bcrypt.compareSync(String(password ?? ''), user.password_hash)) {
    res.status(401).json({ error: 'Invalid email or password' })
    return
  }
  setSession(res, user.id)
  res.json({ id: user.id, email: user.email })
})

app.post('/api/auth/logout', (_req, res) => {
  res.clearCookie(COOKIE)
  res.json({ ok: true })
})

app.get('/api/auth/me', (req, res) => {
  const uid = getUserId(req)
  if (uid === null) {
    res.json({ user: null })
    return
  }
  const user = db.prepare('SELECT id, email FROM users WHERE id = ?').get(uid)
  res.json({ user: user ?? null })
})

// --- Learning progress ---------------------------------------------------

app.get('/api/progress', requireAuth, (req: AuthedRequest, res) => {
  const rows = db
    .prepare('SELECT constellation FROM progress WHERE user_id = ?')
    .all(req.userId) as { constellation: string }[]
  res.json({ learned: rows.map((r) => r.constellation) })
})

app.put('/api/progress/:constellation', requireAuth, (req: AuthedRequest, res) => {
  const abbr = req.params.constellation
  const { learned } = req.body ?? {}
  if (learned) {
    db.prepare(
      'INSERT OR IGNORE INTO progress (user_id, constellation) VALUES (?, ?)',
    ).run(req.userId, abbr)
  } else {
    db.prepare('DELETE FROM progress WHERE user_id = ? AND constellation = ?').run(
      req.userId,
      abbr,
    )
  }
  res.json({ ok: true })
})

// --- Quiz results ----------------------------------------------------------

app.post('/api/quiz-results', requireAuth, (req: AuthedRequest, res) => {
  const { score, total } = req.body ?? {}
  if (!Number.isInteger(score) || !Number.isInteger(total) || total <= 0 || score < 0 || score > total) {
    res.status(400).json({ error: 'Invalid score' })
    return
  }
  db.prepare('INSERT INTO quiz_results (user_id, score, total) VALUES (?, ?, ?)').run(
    req.userId,
    score,
    total,
  )
  res.status(201).json({ ok: true })
})

app.get('/api/quiz-results', requireAuth, (req: AuthedRequest, res) => {
  const rows = db
    .prepare(
      'SELECT score, total, created_at FROM quiz_results WHERE user_id = ? ORDER BY created_at DESC LIMIT 20',
    )
    .all(req.userId)
  res.json({ results: rows })
})

app.listen(PORT, () => {
  console.log(`Constellation Teacher API listening on http://localhost:${PORT}`)
})
